services:
    _defaults:
        public: false

    yamilovs_sms.prototype.provider.sms_ru:
        class: Yamilovs\Bundle\SmsBundle\Provider\SmsruProvider

    yamilovs_sms.provider.manager:
        class: Yamilovs\Bundle\SmsBundle\Service\ProviderManager

    Yamilovs\Bundle\SmsBundle\Service\ProviderManager: '@yamilovs_sms.provider.manager'